### ISSUE TITLE
failed at test unit and integration

### ISSUE THREAD

**Issue by callumparr** [dewyman/TALON#38]
I am having issues getting python3.7 installed and currently version is 3.6.0 for python3. 

make tests works with some warning,

but then make unit and make integration fail for most tests 

I attach output. 

Is this to be expected without using python3.7? 

In any case I can get talon scripts to run and output in same environment 
[error_output.txt](https://github.com/dewyman/TALON/files/3349609/error_output.txt)

**Comment by dewyman** [comment]
Hi Callum, 
I set up a Conda environment with Python 3.6 and all of the tests still passed on my machine. I had my colleague run the testing suite as well, and she had similar issues to yours, so I think the problem might be as simple as missing test data files from the repo, or maybe an errant path. I'll look into it.

**Comment by callumparr** [comment]
Thank you. 

I got the talon.py working in python 3.6, I can see some novel annotations from TALON.
