### ISSUE TITLE
How do I use the create talon report R scrip

### ISSUE THREAD

**Issue by callumparr** [dewyman/TALON#40]
Sorry for all the questions. 

I would like to use the R script to generate plots from my db generated through talon scripts. 

I am not so familiar and I do not know how to input my files.

**Comment by dewyman** [comment]
No problem! I'm happy to help :) Here is how to run the report script. It generates the following figures in PNG format, and also prints out some metrics to the terminal:
- Transcript TPM distribution  
- Gene TPM distribution. 
- Transcript length distribution by annotation status. 
- Distribution of number of isoforms per gene. 
- Exons per read by annotation status.

We have additional analysis scripts on our TALON-paper-2019 repo here, many of which are designed for datasets with biological replicates. https://github.com/dewyman/TALON-paper-2019/tree/master/analysis_scripts

Rscript post-TALON_tools/generate_talon_report.R --help

Options:
	--db=DB
		TALON database file

	-w WHITELISTS, --whitelists=WHITELISTS
		Comma-delimited list of up to two filenames. File contains whitelisted transcripts for the datasets provided. If this option is omitted, all genes and transcripts are included in the analyses.

	--datasets=DATASETS
		Comma-delimited list of up to two dataset names to include in the analysis.

	-o OUTDIR, --outdir=OUTDIR
		Output directory for plots and outfiles

	-h, --help
		Show this help message and exit

**Comment by callumparr** [comment]
@dewyman 

May I confirm with you that there is a hard upper limit on the number of datasets (two) that can be passed to talon_generate_report tool? 

I ran TALON through my datasets, with 8 different conditions and around 3 to 4 biological replicates per condition. Should I run this several times or is there a way to pass more datasets?

**Comment by fairliereese** [comment]
Hi there,

I haven't personally run this tool before but after looking at the code, it looks like it unfortunately only accepts one dataset. I think the easiest workaround would be to run it multiple times!

**Comment by callumparr** [comment]
> Hi there,
> 
> I haven't personally run this tool before but after looking at the code, it looks like it unfortunately only accepts one dataset. I think the easiest workaround would be to run it multiple times!

TY will do this.
