### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by ashokpatowary** [dewyman/TALON#47]
Hi,

I was trying to run talon on my minion data. But I am encountering index error. Bellow is the error. Can you please look into it.

Thanks

[ 2019-11-13 23:44:23 ] Started TALON run
Traceback (most recent call last):
  File "/usr/local/bin/talon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/talon/talon.py", line 2346, in main
    sam_files, dset_metadata = check_inputs(options)
  File "/usr/local/lib/python3.7/site-packages/talon/talon.py", line 1411, in check_inputs
    curr_sam = line[3]
IndexError: list index out of range

**Comment by dewyman** [comment]
Hi,
Can you show me what your config file looks like? This error suggests to me that you may not have the correct number of comma-delimited fields in it.
Best,
Dana

**Comment by ashokpatowary** [comment]
Hi.

Here is my config file looks like

AllRNA,HFB1,MinION,/Users/Ashok/Desktop/Hoffman/ashokpat/MinION/11042019/HFB.sam

**Comment by dewyman** [comment]
Ok, that looks reasonable. But is there by any chance a blank line underneath this entry? That has happened to my labmate before.

**Comment by ashokpatowary** [comment]
Yes. There was a blank line underneath. And I delete that line. Its working perfect now. Thanks

**Comment by dewyman** [comment]
Glad to hear it! Let me know if you have more questions :)

**Comment by ashokpatowary** [comment]
Hi @dewyman,

It runs fine but while generating the read_annot.tvs file I have the following error. Can you look into it?

[ 2019-11-15 04:25:53 ] All jobs complete. Starting database update.
[ 2019-11-15 04:29:02 ] Validating database........
[ 2019-11-15 04:29:03 ] Database update complete.
[ 2019-11-15 04:29:03 ] Creating read-wise annotation file.
Traceback (most recent call last):
  File "/usr/local/bin/talon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/talon/talon.py", line 2419, in main
    outprefix, datasets = datasets)
  File "/usr/local/lib/python3.7/site-packages/talon/post/get_read_annotations.py", line 372, in make_read_annot_file
    curr_gene_novelty = gene_novelty[gene_ID]
KeyError: 46490

**Comment by dewyman** [comment]
Hi,
It looks like the script that generates the output file is having trouble finding the novelty status of the gene with ID '46490'. This is something I should be able to patch for you relatively quickly, but I'd like to understand why it's happening to solve the underlying issue. Would you mind sending me the TALON database that was the output of your run?

**Comment by ashokpatowary** [comment]
Sure. I am sending it to you.

**Comment by dewyman** [comment]
Ok I was able to figure out what is going on. The gene with TALON id '46490' is ENSG00000272675.1, which has a 'NOVEL' gene_status designation in the GENCODE GTF you provided. This confused the TALON read_annot utility because it was expecting 3 only different types of genes: Known (by virtue of the annotation), antisense novel, or intergenic novel (these latter two cases are called by TALON).  

One thing I can do is add a try/except clause to the novelty lookup in the read_annot script so that when this type of issue happens, the novelty assignment in the outfile will be 'Other' rather than crashing the whole thing. Would that make sense for you?

**Comment by ashokpatowary** [comment]
Yah Sure. That should be fine.

**Comment by ashokpatowary** [comment]
Yah Sure. That should be fine. I am using Gencode v32

**Comment by dewyman** [comment]
Ok, I have implemented the patch now, so feel free to clone from the master branch and try it out. You do not need to redo your TALON run since all the jobs/database updates ran fine- all you need to do is run the talon_fetch_reads utility to get your output file:

```
talon_fetch_reads --h

Usage: talon_fetch_reads [-h] [--db FILE,] [--build STRING,]
                         [--datasets STRING,] [--o OUTPREFIX]

This utility queries a TALON database in order to get read-specific annotation
information.

optional arguments:
  -h, --help          show this help message and exit
  --db FILE,          TALON database
  --build STRING,     Genome build (i.e. hg38) to use. Must be in the
                      database.
  --datasets STRING,  Optional: Comma-delimited list of datasets to include.
                      Default behavior is to include all datasets in the
                      database.
  --o OUTPREFIX       Prefix for output files
```

Let me know how it goes!

**Comment by ashokpatowary** [comment]
Thanks. The output file generated without any error.
