### ISSUE TITLE
UNIQUE constraint failed: dataset.dataset_ID

### ISSUE THREAD

**Issue by signor-molevol** [dewyman/TALON#50]
This is happening at the end of about 1/2 of my runs for talon, with other combinations of .sam files, config files, and db's working just fine. 

For example, this command produces the error:

talon --f ../TranscriptClean-master/config.csv --db ds2.2.db --build ds2.2 --threads 4 --o talon_out1

and this does not:

talon --f ../TranscriptClean-master/config_2.csv --db ds2.2.db --build ds2.2 --threads 4 --o talon_out2

The difference of course being which sam file is in the config file. The sam files were all produced by TranscriptClean after mapping by minimap2. I checked for non-unique read headers, there are none. 

Any help on tracking down this error would be helpful.

**Comment by dewyman** [comment]
Hello, I think the problem here is that you have given two datasets the same name in your configuration files (i.e. the first column). Could you check if that is the case?
All the best,
Dana

**Comment by signor-molevol** [comment]
Hi Dana,

Yes, I keep changing the names to investigate that possibility, and that isn't it.

Thanks, Sarah

________________________________

**Comment by dewyman** [comment]
Hi Sarah,
Out of curiosity, do you get the same error when you combine the two config files into one and run all of the datasets at once? Also, which TALON version are you running?
Thanks,
Dana

**Comment by signor-molevol** [comment]
In case anyone else comes across this, and so the issue can be closed, the problem was that I needed to reinitialize the database when I started with a new sample.
