### ISSUE TITLE
pip install talon  doesn't work?

### ISSUE THREAD

**Issue by luckylyw** [dewyman/TALON#51]
Hello!

   When I use PIP install talon, the installation is successful, but the command such as Talon is not displayed.  
<img width="439" alt="image" src="https://user-images.githubusercontent.com/31990103/76168098-341d7580-61a7-11ea-800c-85969e99a08c.png">

**Comment by dewyman** [comment]
Hello,
What was the pip command that you used?
Best,
Dana

**Comment by luckylyw** [comment]
pip3 install talon

**Comment by dewyman** [comment]
Ok, I see the problem. We haven't actually added TALON to PyPI, so pip install talon does not work. What you will need to do instead is download the TALON release [here](https://github.com/dewyman/TALON/releases/tag/4.4.2), cd into the directory once you've downloaded and unzipped it, and then run 'pip install .' Then it should work.

**Comment by luckylyw** [comment]
Thanks for your answer. I have successfully installed Talon！！！

**Comment by dewyman** [comment]
Great! Happy to help.
